/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReadRouteImport } from './routes/read'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HanjaRouteImport } from './routes/hanja'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiQuizSubmitRouteImport } from './routes/api/quiz-submit'
import { Route as ApiGenerateCandyRouteImport } from './routes/api/generate-candy'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCoursesLevelIdRouteImport } from './routes/_authenticated/courses.$levelId'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HanjaRoute = HanjaRouteImport.update({
  id: '/hanja',
  path: '/hanja',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizSubmitRoute = ApiQuizSubmitRouteImport.update({
  id: '/api/quiz-submit',
  path: '/api/quiz-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCandyRoute = ApiGenerateCandyRouteImport.update({
  id: '/api/generate-candy',
  path: '/api/generate-candy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesLevelIdRoute =
  AuthenticatedCoursesLevelIdRouteImport.update({
    id: '/$levelId',
    path: '/$levelId',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/hanja': typeof HanjaRoute
  '/library': typeof LibraryRoute
  '/read': typeof ReadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study': typeof StudyRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-candy': typeof ApiGenerateCandyRoute
  '/api/quiz-submit': typeof ApiQuizSubmitRoute
  '/api/translate': typeof ApiTranslateRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/courses/$levelId': typeof AuthenticatedCoursesLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hanja': typeof HanjaRoute
  '/library': typeof LibraryRoute
  '/read': typeof ReadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study': typeof StudyRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-candy': typeof ApiGenerateCandyRoute
  '/api/quiz-submit': typeof ApiQuizSubmitRoute
  '/api/translate': typeof ApiTranslateRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat': typeof ChatIndexRoute
  '/courses/$levelId': typeof AuthenticatedCoursesLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/hanja': typeof HanjaRoute
  '/library': typeof LibraryRoute
  '/read': typeof ReadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study': typeof StudyRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-candy': typeof ApiGenerateCandyRoute
  '/api/quiz-submit': typeof ApiQuizSubmitRoute
  '/api/translate': typeof ApiTranslateRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/_authenticated/courses/$levelId': typeof AuthenticatedCoursesLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/hanja'
    | '/library'
    | '/read'
    | '/sitemap.xml'
    | '/study'
    | '/courses'
    | '/home'
    | '/onboarding'
    | '/quiz'
    | '/api/chat'
    | '/api/generate-candy'
    | '/api/quiz-submit'
    | '/api/translate'
    | '/chat/$threadId'
    | '/chat/'
    | '/courses/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/hanja'
    | '/library'
    | '/read'
    | '/sitemap.xml'
    | '/study'
    | '/courses'
    | '/home'
    | '/onboarding'
    | '/quiz'
    | '/api/chat'
    | '/api/generate-candy'
    | '/api/quiz-submit'
    | '/api/translate'
    | '/chat/$threadId'
    | '/chat'
    | '/courses/$levelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chat'
    | '/hanja'
    | '/library'
    | '/read'
    | '/sitemap.xml'
    | '/study'
    | '/_authenticated/courses'
    | '/_authenticated/home'
    | '/_authenticated/onboarding'
    | '/_authenticated/quiz'
    | '/api/chat'
    | '/api/generate-candy'
    | '/api/quiz-submit'
    | '/api/translate'
    | '/chat/$threadId'
    | '/chat/'
    | '/_authenticated/courses/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRouteWithChildren
  HanjaRoute: typeof HanjaRoute
  LibraryRoute: typeof LibraryRoute
  ReadRoute: typeof ReadRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyRoute: typeof StudyRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateCandyRoute: typeof ApiGenerateCandyRoute
  ApiQuizSubmitRoute: typeof ApiQuizSubmitRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hanja': {
      id: '/hanja'
      path: '/hanja'
      fullPath: '/hanja'
      preLoaderRoute: typeof HanjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz-submit': {
      id: '/api/quiz-submit'
      path: '/api/quiz-submit'
      fullPath: '/api/quiz-submit'
      preLoaderRoute: typeof ApiQuizSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-candy': {
      id: '/api/generate-candy'
      path: '/api/generate-candy'
      fullPath: '/api/generate-candy'
      preLoaderRoute: typeof ApiGenerateCandyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$levelId': {
      id: '/_authenticated/courses/$levelId'
      path: '/$levelId'
      fullPath: '/courses/$levelId'
      preLoaderRoute: typeof AuthenticatedCoursesLevelIdRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
  }
}

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesLevelIdRoute: typeof AuthenticatedCoursesLevelIdRoute
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesLevelIdRoute: AuthenticatedCoursesLevelIdRoute,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRouteWithChildren,
  HanjaRoute: HanjaRoute,
  LibraryRoute: LibraryRoute,
  ReadRoute: ReadRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyRoute: StudyRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateCandyRoute: ApiGenerateCandyRoute,
  ApiQuizSubmitRoute: ApiQuizSubmitRoute,
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
