
-- Expand Hanja dataset
INSERT INTO public.hanja (character, korean_reading, meaning, romanization, examples, notes) VALUES
('時','시','time','si','[{"word":"시간","reading":"시간","meaning":"time, hour"},{"word":"시계","reading":"시계","meaning":"clock"},{"word":"시대","reading":"시대","meaning":"era"}]'::jsonb,null),
('間','간','interval, between','gan','[{"word":"시간","reading":"시간","meaning":"time"},{"word":"공간","reading":"공간","meaning":"space"},{"word":"인간","reading":"인간","meaning":"human"}]'::jsonb,null),
('人','인','person','in','[{"word":"한국인","reading":"한국인","meaning":"Korean person"},{"word":"개인","reading":"개인","meaning":"individual"},{"word":"인구","reading":"인구","meaning":"population"}]'::jsonb,null),
('生','생','life, birth','saeng','[{"word":"학생","reading":"학생","meaning":"student"},{"word":"생일","reading":"생일","meaning":"birthday"},{"word":"인생","reading":"인생","meaning":"life"}]'::jsonb,null),
('學','학','study, learn','hak','[{"word":"학교","reading":"학교","meaning":"school"},{"word":"학생","reading":"학생","meaning":"student"},{"word":"대학","reading":"대학","meaning":"university"}]'::jsonb,null),
('校','교','school','gyo','[{"word":"학교","reading":"학교","meaning":"school"},{"word":"교실","reading":"교실","meaning":"classroom"},{"word":"교복","reading":"교복","meaning":"uniform"}]'::jsonb,null),
('家','가','house, family','ga','[{"word":"가족","reading":"가족","meaning":"family"},{"word":"국가","reading":"국가","meaning":"nation"},{"word":"작가","reading":"작가","meaning":"writer"}]'::jsonb,null),
('國','국','country','guk','[{"word":"한국","reading":"한국","meaning":"Korea"},{"word":"외국","reading":"외국","meaning":"foreign country"},{"word":"국민","reading":"국민","meaning":"people of a nation"}]'::jsonb,null),
('語','어','language','eo','[{"word":"한국어","reading":"한국어","meaning":"Korean language"},{"word":"외국어","reading":"외국어","meaning":"foreign language"},{"word":"단어","reading":"단어","meaning":"word"}]'::jsonb,null),
('文','문','writing, text','mun','[{"word":"문화","reading":"문화","meaning":"culture"},{"word":"문장","reading":"문장","meaning":"sentence"},{"word":"한문","reading":"한문","meaning":"Chinese writing"}]'::jsonb,null),
('字','자','character, letter','ja','[{"word":"한자","reading":"한자","meaning":"Hanja"},{"word":"숫자","reading":"숫자","meaning":"number"},{"word":"글자","reading":"글자","meaning":"letter"}]'::jsonb,null),
('日','일','day, sun','il','[{"word":"일요일","reading":"일요일","meaning":"Sunday"},{"word":"생일","reading":"생일","meaning":"birthday"},{"word":"매일","reading":"매일","meaning":"every day"}]'::jsonb,null),
('月','월','moon, month','wol','[{"word":"월요일","reading":"월요일","meaning":"Monday"},{"word":"이월","reading":"이월","meaning":"February"},{"word":"개월","reading":"개월","meaning":"months (counter)"}]'::jsonb,null),
('火','화','fire','hwa','[{"word":"화요일","reading":"화요일","meaning":"Tuesday"},{"word":"화재","reading":"화재","meaning":"fire (disaster)"},{"word":"화산","reading":"화산","meaning":"volcano"}]'::jsonb,null),
('水','수','water','su','[{"word":"수요일","reading":"수요일","meaning":"Wednesday"},{"word":"홍수","reading":"홍수","meaning":"flood"},{"word":"수영","reading":"수영","meaning":"swimming"}]'::jsonb,null),
('木','목','tree, wood','mok','[{"word":"목요일","reading":"목요일","meaning":"Thursday"},{"word":"식목","reading":"식목","meaning":"tree planting"},{"word":"목재","reading":"목재","meaning":"timber"}]'::jsonb,null),
('金','금','gold, metal','geum','[{"word":"금요일","reading":"금요일","meaning":"Friday"},{"word":"황금","reading":"황금","meaning":"gold"},{"word":"현금","reading":"현금","meaning":"cash"}]'::jsonb,null),
('土','토','earth, soil','to','[{"word":"토요일","reading":"토요일","meaning":"Saturday"},{"word":"국토","reading":"국토","meaning":"national territory"},{"word":"토양","reading":"토양","meaning":"soil"}]'::jsonb,null),
('年','년','year','nyeon','[{"word":"작년","reading":"작년","meaning":"last year"},{"word":"내년","reading":"내년","meaning":"next year"},{"word":"청년","reading":"청년","meaning":"youth"}]'::jsonb,null),
('大','대','big, great','dae','[{"word":"대학교","reading":"대학교","meaning":"university"},{"word":"대한민국","reading":"대한민국","meaning":"Republic of Korea"},{"word":"대화","reading":"대화","meaning":"conversation"}]'::jsonb,null),
('小','소','small','so','[{"word":"소년","reading":"소년","meaning":"boy"},{"word":"소설","reading":"소설","meaning":"novel"},{"word":"축소","reading":"축소","meaning":"reduction"}]'::jsonb,null),
('中','중','middle','jung','[{"word":"중국","reading":"중국","meaning":"China"},{"word":"중간","reading":"중간","meaning":"middle"},{"word":"집중","reading":"집중","meaning":"concentration"}]'::jsonb,null),
('上','상','up, above','sang','[{"word":"상관","reading":"상관","meaning":"relation, boss"},{"word":"이상","reading":"이상","meaning":"more than"},{"word":"상황","reading":"상황","meaning":"situation"}]'::jsonb,null),
('下','하','down, below','ha','[{"word":"이하","reading":"이하","meaning":"less than"},{"word":"하차","reading":"하차","meaning":"getting off"},{"word":"하루","reading":"하루","meaning":"one day"}]'::jsonb,null),
('東','동','east','dong','[{"word":"동쪽","reading":"동쪽","meaning":"east side"},{"word":"동대문","reading":"동대문","meaning":"Dongdaemun"},{"word":"동양","reading":"동양","meaning":"the East"}]'::jsonb,null),
('西','서','west','seo','[{"word":"서울","reading":"서울","meaning":"Seoul"},{"word":"서양","reading":"서양","meaning":"the West"},{"word":"서쪽","reading":"서쪽","meaning":"west side"}]'::jsonb,null),
('南','남','south','nam','[{"word":"남자","reading":"남자","meaning":"man"},{"word":"남쪽","reading":"남쪽","meaning":"south"},{"word":"남편","reading":"남편","meaning":"husband"}]'::jsonb,null),
('北','북','north','buk','[{"word":"북한","reading":"북한","meaning":"North Korea"},{"word":"북쪽","reading":"북쪽","meaning":"north side"},{"word":"동북","reading":"동북","meaning":"northeast"}]'::jsonb,null),
('白','백','white, hundred','baek','[{"word":"백화점","reading":"백화점","meaning":"department store"},{"word":"백색","reading":"백색","meaning":"white color"},{"word":"고백","reading":"고백","meaning":"confession"}]'::jsonb,null),
('黑','흑','black','heuk','[{"word":"흑백","reading":"흑백","meaning":"black and white"},{"word":"흑인","reading":"흑인","meaning":"black person"},{"word":"암흑","reading":"암흑","meaning":"darkness"}]'::jsonb,null),
('心','심','heart, mind','sim','[{"word":"중심","reading":"중심","meaning":"center"},{"word":"관심","reading":"관심","meaning":"interest"},{"word":"안심","reading":"안심","meaning":"relief"}]'::jsonb,null),
('愛','애','love','ae','[{"word":"애인","reading":"애인","meaning":"lover"},{"word":"사랑","reading":"사랑","meaning":"love (native)"},{"word":"애정","reading":"애정","meaning":"affection"}]'::jsonb,null),
('友','우','friend','u','[{"word":"친우","reading":"친우","meaning":"close friend"},{"word":"우정","reading":"우정","meaning":"friendship"},{"word":"학우","reading":"학우","meaning":"schoolmate"}]'::jsonb,null),
('父','부','father','bu','[{"word":"부모","reading":"부모","meaning":"parents"},{"word":"조부","reading":"조부","meaning":"grandfather"},{"word":"학부모","reading":"학부모","meaning":"parent (school)"}]'::jsonb,null),
('母','모','mother','mo','[{"word":"부모","reading":"부모","meaning":"parents"},{"word":"모성","reading":"모성","meaning":"motherhood"},{"word":"이모","reading":"이모","meaning":"aunt (maternal)"}]'::jsonb,null),
('子','자','child','ja','[{"word":"여자","reading":"여자","meaning":"woman"},{"word":"남자","reading":"남자","meaning":"man"},{"word":"자녀","reading":"자녀","meaning":"children"}]'::jsonb,null),
('女','여','woman','yeo','[{"word":"여자","reading":"여자","meaning":"woman"},{"word":"여성","reading":"여성","meaning":"female"},{"word":"여왕","reading":"여왕","meaning":"queen"}]'::jsonb,null),
('男','남','man','nam','[{"word":"남자","reading":"남자","meaning":"man"},{"word":"남성","reading":"남성","meaning":"male"},{"word":"미남","reading":"미남","meaning":"handsome man"}]'::jsonb,null),
('王','왕','king','wang','[{"word":"왕자","reading":"왕자","meaning":"prince"},{"word":"왕국","reading":"왕국","meaning":"kingdom"},{"word":"국왕","reading":"국왕","meaning":"monarch"}]'::jsonb,null),
('民','민','people','min','[{"word":"국민","reading":"국민","meaning":"citizens"},{"word":"민족","reading":"민족","meaning":"ethnic people"},{"word":"농민","reading":"농민","meaning":"farmer"}]'::jsonb,null),
('車','차','vehicle, car','cha','[{"word":"자동차","reading":"자동차","meaning":"automobile"},{"word":"기차","reading":"기차","meaning":"train"},{"word":"차도","reading":"차도","meaning":"roadway"}]'::jsonb,null),
('道','도','way, road','do','[{"word":"도로","reading":"도로","meaning":"road"},{"word":"도서관","reading":"도서관","meaning":"library"},{"word":"인도","reading":"인도","meaning":"sidewalk"}]'::jsonb,null),
('食','식','eat, food','sik','[{"word":"음식","reading":"음식","meaning":"food"},{"word":"식당","reading":"식당","meaning":"restaurant"},{"word":"식사","reading":"식사","meaning":"meal"}]'::jsonb,null),
('飮','음','drink','eum','[{"word":"음료","reading":"음료","meaning":"beverage"},{"word":"음식","reading":"음식","meaning":"food and drink"},{"word":"음주","reading":"음주","meaning":"drinking"}]'::jsonb,null),
('衣','의','clothes','ui','[{"word":"의복","reading":"의복","meaning":"clothing"},{"word":"의상","reading":"의상","meaning":"costume"},{"word":"한복","reading":"한복","meaning":"hanbok"}]'::jsonb,null),
('住','주','live, reside','ju','[{"word":"주소","reading":"주소","meaning":"address"},{"word":"주민","reading":"주민","meaning":"resident"},{"word":"거주","reading":"거주","meaning":"residence"}]'::jsonb,null),
('業','업','work, business','eop','[{"word":"직업","reading":"직업","meaning":"occupation"},{"word":"사업","reading":"사업","meaning":"business"},{"word":"학업","reading":"학업","meaning":"academics"}]'::jsonb,null),
('社','사','company, society','sa','[{"word":"회사","reading":"회사","meaning":"company"},{"word":"사회","reading":"사회","meaning":"society"},{"word":"신문사","reading":"신문사","meaning":"newspaper company"}]'::jsonb,null),
('會','회','meeting','hoe','[{"word":"회의","reading":"회의","meaning":"meeting"},{"word":"기회","reading":"기회","meaning":"opportunity"},{"word":"사회","reading":"사회","meaning":"society"}]'::jsonb,null),
('話','화','speech, talk','hwa','[{"word":"대화","reading":"대화","meaning":"conversation"},{"word":"전화","reading":"전화","meaning":"telephone"},{"word":"동화","reading":"동화","meaning":"fairy tale"}]'::jsonb,null),
('音','음','sound','eum','[{"word":"음악","reading":"음악","meaning":"music"},{"word":"발음","reading":"발음","meaning":"pronunciation"},{"word":"녹음","reading":"녹음","meaning":"recording"}]'::jsonb,null),
('樂','악','music; pleasure','ak','[{"word":"음악","reading":"음악","meaning":"music"},{"word":"오락","reading":"오락","meaning":"entertainment"},{"word":"낙원","reading":"낙원","meaning":"paradise"}]'::jsonb,null),
('心','심','heart','sim','[{"word":"마음","reading":"마음","meaning":"heart, mind"},{"word":"양심","reading":"양심","meaning":"conscience"},{"word":"진심","reading":"진심","meaning":"sincerity"}]'::jsonb,null),
('力','력','power, strength','ryeok','[{"word":"능력","reading":"능력","meaning":"ability"},{"word":"노력","reading":"노력","meaning":"effort"},{"word":"실력","reading":"실력","meaning":"skill"}]'::jsonb,null),
('明','명','bright, clear','myeong','[{"word":"설명","reading":"설명","meaning":"explanation"},{"word":"분명","reading":"분명","meaning":"clearly"},{"word":"명단","reading":"명단","meaning":"list of names"}]'::jsonb,null),
('正','정','correct, right','jeong','[{"word":"정답","reading":"정답","meaning":"correct answer"},{"word":"정확","reading":"정확","meaning":"accurate"},{"word":"정의","reading":"정의","meaning":"justice"}]'::jsonb,null),
('安','안','peaceful, safe','an','[{"word":"안전","reading":"안전","meaning":"safety"},{"word":"안녕","reading":"안녕","meaning":"hello/peace"},{"word":"불안","reading":"불안","meaning":"anxiety"}]'::jsonb,null),
('全','전','all, whole','jeon','[{"word":"안전","reading":"안전","meaning":"safety"},{"word":"전부","reading":"전부","meaning":"all"},{"word":"전국","reading":"전국","meaning":"nationwide"}]'::jsonb,null),
('新','신','new','sin','[{"word":"신문","reading":"신문","meaning":"newspaper"},{"word":"신년","reading":"신년","meaning":"new year"},{"word":"혁신","reading":"혁신","meaning":"innovation"}]'::jsonb,null),
('聞','문','hear','mun','[{"word":"신문","reading":"신문","meaning":"newspaper"},{"word":"소문","reading":"소문","meaning":"rumor"},{"word":"청문회","reading":"청문회","meaning":"hearing"}]'::jsonb,null),
('行','행','go, act','haeng','[{"word":"여행","reading":"여행","meaning":"travel"},{"word":"행동","reading":"행동","meaning":"action"},{"word":"은행","reading":"은행","meaning":"bank"}]'::jsonb,null),
('來','래','come','rae','[{"word":"미래","reading":"미래","meaning":"future"},{"word":"내일","reading":"내일","meaning":"tomorrow"},{"word":"외래","reading":"외래","meaning":"foreign"}]'::jsonb,null),
('前','전','front, before','jeon','[{"word":"이전","reading":"이전","meaning":"before"},{"word":"오전","reading":"오전","meaning":"morning (AM)"},{"word":"앞","reading":"앞","meaning":"front (native)"}]'::jsonb,null),
('後','후','after, behind','hu','[{"word":"오후","reading":"오후","meaning":"afternoon"},{"word":"이후","reading":"이후","meaning":"after"},{"word":"최후","reading":"최후","meaning":"the last"}]'::jsonb,null),
('力','력','power','ryeok','[{"word":"권력","reading":"권력","meaning":"authority"},{"word":"체력","reading":"체력","meaning":"stamina"},{"word":"전력","reading":"전력","meaning":"electricity, full force"}]'::jsonb,null)
ON CONFLICT DO NOTHING;

-- Grammar patterns reference table
CREATE TABLE IF NOT EXISTS public.grammar_patterns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pattern text NOT NULL UNIQUE,
  level text NOT NULL DEFAULT 'L2',
  meaning text NOT NULL,
  structure text,
  examples jsonb NOT NULL DEFAULT '[]'::jsonb,
  tags text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.grammar_patterns TO anon, authenticated;
GRANT ALL ON public.grammar_patterns TO service_role;
ALTER TABLE public.grammar_patterns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "grammar_patterns_public_read" ON public.grammar_patterns FOR SELECT TO anon, authenticated USING (true);

INSERT INTO public.grammar_patterns (pattern, level, meaning, structure, examples, tags) VALUES
('-아서/어서','L1','because (cause/reason, joined to verb stem)','V-아서/어서 + result clause','[{"ko":"비가 와서 우산을 가져왔어요.","en":"It was raining, so I brought an umbrella."},{"ko":"피곤해서 일찍 잤어요.","en":"I was tired, so I slept early."}]'::jsonb,'{cause,connective}'),
('-(으)니까','L2','because/since (speaker-centered reason)','V-(으)니까 + clause','[{"ko":"시간이 없으니까 빨리 가요.","en":"Since there''s no time, let''s hurry."},{"ko":"맛있으니까 더 먹어요.","en":"It''s delicious, so eat more."}]'::jsonb,'{cause,connective}'),
('-(으)면','L1','if / when','V-(으)면 + clause','[{"ko":"비가 오면 안 갈 거예요.","en":"If it rains, I won''t go."},{"ko":"심심하면 전화해요.","en":"Call me if you''re bored."}]'::jsonb,'{conditional}'),
('-고 있다','L1','progressive (be ~ing)','V-고 있다','[{"ko":"지금 책을 읽고 있어요.","en":"I''m reading a book now."},{"ko":"동생이 자고 있어요.","en":"My sibling is sleeping."}]'::jsonb,'{tense,aspect}'),
('-았/었어요','L1','past polite','V-았/었어요','[{"ko":"어제 영화를 봤어요.","en":"I watched a movie yesterday."},{"ko":"밥을 먹었어요.","en":"I ate."}]'::jsonb,'{tense}'),
('-(으)ㄹ 거예요','L1','will / probably','V-(으)ㄹ 거예요','[{"ko":"내일 갈 거예요.","en":"I''ll go tomorrow."},{"ko":"비가 올 거예요.","en":"It will probably rain."}]'::jsonb,'{future,tense}'),
('-(으)러','L1','in order to (with go/come)','V-(으)러 가다/오다','[{"ko":"밥을 먹으러 가요.","en":"I''m going to eat."},{"ko":"친구를 만나러 왔어요.","en":"I came to meet a friend."}]'::jsonb,'{purpose}'),
('-(으)려고','L2','intending to','V-(으)려고 + clause','[{"ko":"공부하려고 도서관에 갔어요.","en":"I went to the library to study."},{"ko":"사진을 찍으려고 카메라를 샀어요.","en":"I bought a camera to take pictures."}]'::jsonb,'{purpose,intention}'),
('-아/어 주세요','L1','please do (for me)','V-아/어 주세요','[{"ko":"천천히 말해 주세요.","en":"Please speak slowly."},{"ko":"도와주세요.","en":"Please help me."}]'::jsonb,'{request,polite}'),
('-(으)ㄹ 수 있다/없다','L1','can / cannot','V-(으)ㄹ 수 있다','[{"ko":"한국어를 할 수 있어요.","en":"I can speak Korean."},{"ko":"매운 거 못 먹어요.","en":"I can''t eat spicy food."}]'::jsonb,'{ability}'),
('-아/어도 되다','L2','it''s ok to / may','V-아/어도 되다','[{"ko":"여기 앉아도 돼요?","en":"May I sit here?"},{"ko":"이거 먹어도 돼요.","en":"You may eat this."}]'::jsonb,'{permission}'),
('-(으)면 안 되다','L2','must not','V-(으)면 안 되다','[{"ko":"여기서 사진 찍으면 안 돼요.","en":"You must not take photos here."}]'::jsonb,'{prohibition}'),
('-아야/어야 하다','L2','have to / must','V-아야/어야 하다','[{"ko":"내일 일찍 일어나야 해요.","en":"I have to get up early tomorrow."}]'::jsonb,'{obligation}'),
('-는/(으)ㄴ 것 같다','L2','it seems / I think','V-는 것 같다','[{"ko":"비가 오는 것 같아요.","en":"It seems to be raining."},{"ko":"맛있는 것 같아요.","en":"I think it''s delicious."}]'::jsonb,'{guess}'),
('-(으)ㄴ 적이 있다','L2','have done before (experience)','V-(으)ㄴ 적이 있다','[{"ko":"한국에 가 본 적이 있어요.","en":"I''ve been to Korea before."}]'::jsonb,'{experience}'),
('-기 전에','L1','before doing','V-기 전에','[{"ko":"자기 전에 이를 닦아요.","en":"I brush my teeth before sleeping."}]'::jsonb,'{time,sequence}'),
('-(으)ㄴ 후에','L1','after doing','V-(으)ㄴ 후에','[{"ko":"수업이 끝난 후에 만나요.","en":"Let''s meet after class ends."}]'::jsonb,'{time,sequence}'),
('-(으)면서','L2','while doing (simultaneously)','V-(으)면서','[{"ko":"음악을 들으면서 공부해요.","en":"I study while listening to music."}]'::jsonb,'{time,simultaneous}'),
('-(으)니까 (discovery)','L3','discovered that (upon doing)','V-(으)니까 + discovery','[{"ko":"문을 여니까 비가 오고 있었어요.","en":"When I opened the door, it was raining."}]'::jsonb,'{discovery}'),
('-(으)ㄴ/는데','L2','background / contrast (and, but)','V-(으)ㄴ/는데','[{"ko":"오늘은 바쁜데 내일은 시간 있어요.","en":"I''m busy today but free tomorrow."}]'::jsonb,'{connective,contrast}'),
('-거나','L2','or (between clauses)','V-거나','[{"ko":"주말에 책을 읽거나 영화를 봐요.","en":"On weekends I read or watch movies."}]'::jsonb,'{connective,alternative}'),
('-지만','L1','but','V-지만','[{"ko":"비싸지만 맛있어요.","en":"It''s expensive but delicious."}]'::jsonb,'{contrast}'),
('-기 때문에','L2','because of (reason, formal)','V-기 때문에','[{"ko":"바쁘기 때문에 갈 수 없어요.","en":"Because I''m busy, I can''t go."}]'::jsonb,'{cause,formal}'),
('-답니다/-답시다','L3','reported speech / suggestion','V-답니다','[{"ko":"같이 가자고 하답니다.","en":"They say let''s go together."}]'::jsonb,'{reported}'),
('-다고 하다','L3','reported speech (someone said)','V-다고 하다','[{"ko":"비가 온다고 했어요.","en":"They said it''s raining."},{"ko":"내일 만나자고 했어요.","en":"They said let''s meet tomorrow."}]'::jsonb,'{reported}'),
('-자마자','L3','as soon as','V-자마자','[{"ko":"집에 오자마자 잤어요.","en":"As soon as I got home, I slept."}]'::jsonb,'{time}'),
('-(으)ㄹ 때','L2','when (doing)','V-(으)ㄹ 때','[{"ko":"피곤할 때 커피를 마셔요.","en":"When I''m tired I drink coffee."}]'::jsonb,'{time}'),
('-아/어 보다','L2','try doing','V-아/어 보다','[{"ko":"한번 먹어 보세요.","en":"Please try eating it."}]'::jsonb,'{attempt}'),
('-아/어 버리다','L3','do completely / regretfully','V-아/어 버리다','[{"ko":"다 먹어 버렸어요.","en":"I ended up eating it all."}]'::jsonb,'{completion}'),
('-게 되다','L3','come to / end up','V-게 되다','[{"ko":"한국에 살게 되었어요.","en":"I came to live in Korea."}]'::jsonb,'{result}'),
('-(으)ㄹ까요?','L1','shall we? / do you think?','V-(으)ㄹ까요?','[{"ko":"같이 갈까요?","en":"Shall we go together?"},{"ko":"비가 올까요?","en":"Do you think it will rain?"}]'::jsonb,'{question,suggestion}'),
('-아/어야겠다','L3','I really should','V-아/어야겠다','[{"ko":"공부해야겠어요.","en":"I really should study."}]'::jsonb,'{intention}'),
('-(으)ㄹ 줄 알다/모르다','L2','know/don''t know how to','V-(으)ㄹ 줄 알다','[{"ko":"수영할 줄 알아요.","en":"I know how to swim."}]'::jsonb,'{ability}'),
('-기로 하다','L2','decide to','V-기로 하다','[{"ko":"내일 만나기로 했어요.","en":"We decided to meet tomorrow."}]'::jsonb,'{decision}'),
('-는 동안','L2','while / during','V-는 동안','[{"ko":"제가 자는 동안 비가 왔어요.","en":"While I was sleeping it rained."}]'::jsonb,'{time,duration}'),
('-(으)ㄹ 정도로','L4','to the extent that','V-(으)ㄹ 정도로','[{"ko":"눈물이 날 정도로 매워요.","en":"Spicy enough to make me cry."}]'::jsonb,'{degree}'),
('-는 바람에','L4','because of (unexpected negative)','V-는 바람에','[{"ko":"늦잠 자는 바람에 지각했어요.","en":"Because I overslept, I was late."}]'::jsonb,'{cause,negative}'),
('-더라도','L4','even if','V-더라도','[{"ko":"힘들더라도 끝까지 해요.","en":"Even if it''s hard, finish it."}]'::jsonb,'{concession}'),
('-는 한','L4','as long as','V-는 한','[{"ko":"제가 사는 한 도와줄게요.","en":"As long as I live, I''ll help you."}]'::jsonb,'{condition}'),
('-(으)ㄴ/는 척하다','L4','pretend to','V-(으)ㄴ/는 척하다','[{"ko":"자는 척했어요.","en":"I pretended to sleep."}]'::jsonb,'{pretense}')
ON CONFLICT (pattern) DO NOTHING;
